# Generated by Django 5.1.1 on 2024-10-08 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billetterie', '0003_ticket_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='available_tickets',
            new_name='nb_person',
        ),
    ]
