# Generated by Django 5.1.1 on 2024-10-09 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billetterie', '0005_remove_utilisateur_username_alter_utilisateur_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='utilisateur',
            managers=[
            ],
        ),
    ]
