# Generated by Django 5.1.1 on 2024-10-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billetterie', '0006_alter_utilisateur_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
