# Generated by Django 5.1.1 on 2024-10-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billetterie', '0010_transaction_payment_intent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
