# Generated by Django 5.1.1 on 2024-10-12 16:44

import django.utils.crypto
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billetterie', '0011_alter_transaction_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(default=django.utils.crypto.get_random_string, max_length=100, unique=True),
        ),
    ]
