# Generated by Django 5.1.1 on 2024-10-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billetterie', '0012_alter_transaction_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_intent',
            field=models.CharField(blank=True, default='no_intent_yet', max_length=100),
        ),
    ]
