# Generated by Django 5.1.1 on 2024-10-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billetterie', '0013_alter_transaction_payment_intent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_intent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
