# Generated by Django 5.1.1 on 2024-10-12 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billetterie', '0014_alter_transaction_payment_intent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='payment_intent',
            new_name='payment_id',
        ),
    ]
