# Generated by Django 5.1.1 on 2024-10-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billetterie', '0015_rename_payment_intent_transaction_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(default='dCUFYIvzymFx', max_length=100, unique=True),
        ),
    ]
