# Generated by Django 5.1.1 on 2024-10-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billetterie', '0016_alter_transaction_transaction_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='payment_id',
            new_name='payment_intent',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
